---
output:
  html_document:
      toc: yes
      number_sections: no
      toc_float: yes
      theme: united
      highlight: zenburn
geometry: margin=1in
knit: (function(inputFile, encoding) {
  browseURL(
    rmarkdown::render(
      inputFile,
      encoding = encoding,
      output_file = "syllabus.html",
      output_dir = '../documents/'))})
bibliography: '../data/bibliography.bib'

title: "Methods 3: Multilevel Statistical Modeling and Machine Learning"
author: Maxime Sainte-Marie
date: "Autumn 2023"

email: "msaintemarie@gmail.com"
web: "svmiller.com/teaching"
officehours: "\\shrug"
office: "\\shrug"
classroom: "\\shrug"
classhours: "\\shrug"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---

<style type="text/css">
body, td {font-size: 18px; font-family: 'Courier New', monospace;}
code.r{font-size: 18px;}
pre {font-size: 18px}
blockquote {font-size: 18px;}
h{font-family: 'Courier New', monospace;}
h1{text-transform: uppercase}
h2{font-variant: small-caps;}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=F,
                      fig.path = 'figs/',
                      cache.path='cache/',
                      warning=F,
                      message=F)

knitr::opts_chunk$set(
                  fig.process = function(x) {
                      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
                      if (file.rename(x, x2)) x2 else x
                      }
                  )


advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%d", adv)
 tmp <- paste0("W",zadv)
 return(tmp)
}

options(scipen=999)
library(tidyverse)
library(stevemisc)
library(lubridate)
library(rbibutils)
library(bibtex)
library(RefManageR)
library(knitcitations)
library(rcrossref)
#bib <- rbibutils::readBib('../data/bibliography.bib')
#bibtex::read.bib("../data/bibliography.bib")
#myopts <- BibOptions(bib.style = "authoryear", style="latex", first.inits=FALSE, max.names = 20)
biblio <- bibtex::read.bib("../data/bibliography.bib")


# Create a calendar for your syllabus ----
# Source: http://svmiller.com/blog/2020/08/a-ggplot-calendar-for-your-semester/

# 1) what is the first Monday of the semester?
# Any number of ways to identify dates in R, but we'll use {lubridate} and the ymd() function here.
# Format: YYYYMMDD. In this example, 4 January 2021.

mon <- ymd(20210104)

# What are some dates you won't be here? In this example, I had a conference on 7 January 2021.
# Spring Break was 15 March 2021 to 19 March 2021.
not_here_dates <- c(
  # SPSA 2021,
  ymd(20210107),
  # Spring Break
  seq(ymd(20210315),ymd(20210319), by=1))

# You can adjust this as you see fit. Basically: add assignment types (e.g. papers, quizzes).
# My intro class was fairly simple: just exams.
exam_dates <- c(ymd(20210218), ymd(20210401), ymd(20210429))

# What are the full dates of the semester? Here, I'll exclude exam week as I like to do.
# In this case: 6 January to 23 April
semester_dates <- seq(ymd(20210106), ymd(20210423), by=1)

# Custom function for treating the first day of the month as the first week 
# of the month up until the first Sunday (unless Sunday was the start of the month)
wom <- function(date) {
    first <- wday(as.Date(paste(year(date),month(date),1,sep="-")))
    return((mday(date)+(first-2)) %/% 7+1)
  }

# Create a data frame of dates, assign to Cal
tibble(date = seq(ymd(20210101), ymd(20210430), by=1))  %>%
  mutate(mon = lubridate::month(date, label=T, abbr=F), # get month label
         wkdy = weekdays(date, abbreviate=T), # get weekday label
         wkdy = fct_relevel(wkdy, "Sun", "Mon", "Tue", "Wed", "Thu","Fri","Sat"), # make sure Sunday comes first
         semester = ifelse(date %in% semester_dates, 1, 0), # is date part of the semester?
         exams = ifelse(date %in% exam_dates, 1, 0), # is it an exam?
         not_here = ifelse(date %in% not_here_dates, 1, 0), # is it a day off?
         day = lubridate::mday(date), # get day of month to add later as a label
         # Below: our custom wom() function
         week = wom(date)) -> Cal

# Create a category variable, for filling.
# I can probably make this a case_when(), but this will work.

Cal %>%
  mutate(category = NA,
         category = ifelse(semester == 1, "Semester", category),
         category = ifelse(semester == 1 & wkdy %in% c("Tue", "Thu"), "Class Day", category),
         category = ifelse(exams == 1, "Exams", category),
         category = ifelse(is.na(category) | (semester == 1 & not_here == 1), "NA", category)) -> Cal 

Cal %>% 
  ggplot(.,aes(wkdy, week)) +
  # custom theme stuff below
  # theme_steve_web() + 
  theme_bw() +
  theme(panel.grid.major.x = element_blank()) +
  # geom_tile and facet_wrap will do all the heavy lifting
  geom_tile(alpha=0.8, aes(fill=category), color="black", size=.45) +
  facet_wrap(~mon, scales="free", ncol=3) +
  # fill in tiles to make it look more "calendary" (sic)
  geom_text(aes(label=day)) +
  # put your y-axis down, flip it, and reverse it
  scale_y_reverse(breaks=NULL) +
  # manually fill scale colors to something you like...
  scale_fill_manual(values=c("Class Day"="steelblue", 
                             "Semester"="lightsteelblue",
                             "NA" = "white", # I like these whited out...
                             "Exams"="indianred4"),
                    #... but also suppress a label for a non-class semester day
                    breaks=c("Class Day","Exams")) +
  labs(fill = "", x="", y="",
       caption = "Notable dates: SPSA 2021 (7 January), Spring Break (15-19 March)")  -> class_cal
```

## Description

The purpose of the course is to further develop students’ knowledge and skills in statistics and programming.

The course includes instruction on statistical techniques relying on the Generalised Linear Model, including multilevel modelling and basic machine learning procedures (e.g. predictive approaches and validation techniques). The course includes lectures on statistical and machine learning concepts as well as practical exercises in programming.

This course builds on the Methods 1 and 2 courses and provides skills and knowledge needed to understand and apply a wider variety of statistical and machine learning methods. The course prepares students for Bayesian computational modelling in the Methods 4 course, and provides techniques for data analysis relevant to exam projects in Social and Cultural Dynamics in Cognition, and in the Bachelor thesis project.

## Objectives

### Knowledge

In the evaluation of the student’s performance, emphasis is placed on the extent to which the student is able to

- demonstrate understanding of statistical techniques relying on the Generalised Linear Model
- demonstrate understanding of hierarchical modeling methods
- demonstrate understanding of basic machine learning concepts. 

### Skills

In the evaluation of the student’s performance, emphasis is placed on the extent to which the student is able to:

- build and evaluate models of hierarchically structured data
- integrate machine learning procedures in data analysis
- communicate analysis processes, results and interpretation.

### Competences

In the evaluation of the student’s performance, emphasis is placed on the extent to which the student is able to:

- independently decide on data analysis methods, given a data set and a research question
- justify decision making when pre-processing messy data for data analysis.

## Format

Lectures are generally accompanied by readings and other resources. All key content is covered in the lecture. However, reading the accompanying materials is a very good idea as the contents are covered in more details, or from different angles, and in general the readings give you the chance to think through the topic and identify your doubts, which you can then bring up in class or on alternative channels.

Lectures should be as interactive as possible, and any question is welcome at any time during class.

> There are naïve questions, tedious questions, ill-phrased questions, questions put after inadequate self-criticism. But every question is a cry to understand the world. There is no such thing as a dumb question (`r capture.output(print(biblio["sagan2011"]))`)

Alternatively, you can also ask a question anonymously and in writing on a Google Document that will be made available to you for each class. You can write questions there before, during, and after lectures. I'll review it from time to time during and between classes to answer them as adequately as I can, in incremental and iterative fashion.

## Evaluation

The course is aimed at giving you a conceptual and hands-on understanding of estimation and generalizability issues, together with data processing and coding skills. Accordingly, the exam consists in 4 portfolio assignments (indicated as A1 to A4 in the course schedule) challenging you to apply your understanding your understanding and programming skills.

RMarkdown files with instructions for each assignment will be made available online around the time of the relevant class. Both group and one-to-one support from the teacher and the instructors will only be provided during classroom hours. Each assignment will consist of a Github/Gitlab repository with all the code, and a document containing the answers to the questions assigned. You are strongly recommended to submit the assignments during the course, so you can get collective feedback. You must re-submit the whole portfolio - revised according to the feedback - for the final exam. You can submit the full portfolio even if you haven't managed to submit each assignment during the course.

Each assignment can be done alone or in groups. The latter is however strongly recommended, for various reasons. Most obviously, teamwork creates opportunities to establish connections and relationships that can be beneficial to you in the longer term, as it will offer you the opportunity to hone crucial collaboration skills such as communication, leadership, conflict resolution, time management, and resource allocation. But also, the pooling of perspectives, backgrounds, knowledge, skills, working styles, and resources made possible by teamwork will lead to a deeper understanding of the subject matter as well as more comprehensive, exhaustive, and creative work output for you and everyone else involved. Finally, shared responsibility and accountability can increase motivation and dedication, and getting constructive feedback from your teammates can both be a learning and confidence-boosting experience for you. Of course, problems specific to teamwork may arise during this course (communication issues, conflicting schedules, unequal contributions...). While we recommend to tackle these sooner than later, it is important to stress that learning to navigate and overcome these challenges is a valuable aspect of teamwork itself.

## Schedule

Students are expected to read mandatory lectures before each session. **Important: class readings are subject to change, contingent on mitigating circumstances as well as the progress we make as a class**. Attending lectures and regularly checking the course website for updates is thus strongly recommended.

1. Introduction and Refresher
    - Quiz!!!
    - Slides
    - Questions for discussion
    - Setting up your computer
        - Install [latest **R** version](https://mirrors.dotsrc.org/cran/)
        - Install [latest **RStudio** version](https://posit.co/download/rstudio-desktop/)
        - Setup [**Github/Gitlab** with RStudio](https://happygitwithr.com)
    - Mandatory reading
    
        > `r capture.output(print(biblio["dienes2008understanding"]))`
        
    - Recommended readings
    
        > `r capture.output(print(biblio["vasishth2016statistical"]))`
        > 
        > `r capture.output(print(biblio["wickham2023"]))` [https://r4ds.hadley.nz]

        
2. Multilevel Linear Models I
    - Slides
    - Mandatory Reading
    
        > `r capture.output(print(biblio["debruine2021understanding"]))`
        
    - Recommended Readings
    
        > `r capture.output(print(biblio["harrison2018brief"]))`
        >  
        > `r capture.output(print(biblio["winter2019statistics"]))`
        >  
        > `r capture.output(print(biblio["fusaroli2019hearing"]))`
        
3. Multilevel Linear Models II
    - A1: Language Development in ASD. Part II
4. Explanation vs. Prediction (A first case of machine learning)
    - Mandatory Reading
    
        >  `r capture.output(print(biblio["rocca2021putting"]))`
        
    - Recommended Readings
    
        > `r capture.output(print(biblio["chekroud2018validation"]))`
        >  
        > `r capture.output(print(biblio["breiman2001statistical"]))`
        
    - A1: Practical Exercise - Language Development in ASD. Part III
        - [Package & Tutorial](https://github.com/LudvigOlsen/cvms)
        
5. Physiological data and advanced Multilevel Linear Models
    - Mandatory Readings
    
        > `r capture.output(print(biblio["fusaroli2016heart"]))`
        >  
        > `r capture.output(print(biblio["ferrer2013dynamical"]))`
        
    - Recommended Reading
    
        > `r capture.output(print(biblio["konvalinka2023role"]))`
        
    - A2: Analyzing physiological coordination
    
6. Advanced Multilevel Linear Models
    - A2: Analyzing physiological coordination
    
7. Prediction and feature selection
   - Slides
   - Mandatory Readings
   
       > `r capture.output(print(biblio["kuhn2019a"]))`
       
   - A3: Is it possible to diagnose psychiatric condition from voice?
8. Cumulative scientific approaches (meta-analysis) + mid-way evaluation
    - Mandatory Reading
    
        > `r capture.output(print(biblio["parola2020voice"]))`
        
    - Recommended Readings
    
        > `r capture.output(print(biblio["parola2023voice"]))`
        >  
        > `r capture.output(print(biblio["grames2022systematic"]))`
        >  
        > `r capture.output(print(biblio["harrer2021"]))`
        
    - A3: Meta-analysis
8. Classification problems and midway evaluation
    - Slides
    - Recommended Reading
    
        > `r capture.output(print(biblio["kuhn2019b"]))`
        
    - A4: Is it possible to diagnose psychiatric condition from voice?
9. Generalized Multilevel Models and Classification
    - Question on logistic regression and link functions
10. No Lecture
    - A4: Is it possible to diagnose psychiatric condition from voice?
11. Machine Learning pipelines
    - A4
12. Machine Learning pipelines
    - A4
13. Machine Learning Pipelines
    - A4
